services:
  - type: web
    name: queen-beauty-store
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
